/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oneKosmos_UITest;

import java.io.IOException;
import java.io.InputStream;
import java.util.Iterator;
import org.json.JSONException;
import org.json.JSONObject;

import org.apache.commons.io.IOUtils;
import org.json.JSONObject;

public class Library {
	public JSONObject getJson(String fileName) throws IOException {
		InputStream in = getClass().getResourceAsStream(fileName);
		byte[] data = IOUtils.toByteArray(in);
		in.close();
		String content = new String(data);
		return new JSONObject(content);
	}
	
	public JSONObject mergeJsonFiles(JSONObject[] arr) {
           JSONObject merged = new JSONObject();
           for (JSONObject obj : arr) {
               Iterator it = obj.keys();
               while (it.hasNext()) {
                   String key = (String)it.next();
                   merged.put(key, obj.get(key));
               }
           }
           return merged;
    }
}
